SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND NOT EXISTS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID
    AND H.START_DATE <= DATE '2022-11-30'
    AND H.END_DATE >= DATE '2022-11-01'
)
AND (C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) >= 500000
AND (C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
